changesDir: ".changes"
unreleasedDir: "unreleased"
versionExt: "md"
projectsVersionSeparator: "/"

headerPath: "header.tpl.md"

versionFormat: '## {{ .Version }} — {{ .Time.Format "2006-01-02" }}'
kindFormat: "### {{ .Kind }}"
changeFormat: "* {{ .Body }}"

newlines:
  beforeChangelogVersion: 1
  beforeKind: 1
  afterKind: 1
  endOfVersion: 1

kinds:
  - label: "Added"
    auto: "minor"
  - label: "Changed"
    auto: "major"
  - label: "Deprecated"
    auto: "minor"
  - label: "Removed"
    auto: "major"
  - label: "Fixed"
    auto: "patch"
  - label: "Updated"
    auto: "patch"
  - label: "Security"
    auto: "patch"

projects:
  - key: "redhat"
    changelog: "redhat/CHANGELOG.md"
  - key: "golang"
    changelog: "golang/CHANGELOG.md"
  - key: "nodejs"
    changelog: "nodejs/CHANGELOG.md"
  - key: "caddy"
    changelog: "caddy/CHANGELOG.md"
  - key: "github"
    changelog: "github/CHANGELOG.md"
  - key: "jq"
    changelog: "jq/CHANGELOG.md"
  - key: "hugo"
    changelog: "hugo/CHANGELOG.md"
  - key: "sass"
    changelog: "sass/CHANGELOG.md"
  - key: "argocd"
    changelog: "argocd/CHANGELOG.md"
  - key: "kroki"
    changelog: "kroki/CHANGELOG.md"
  - key: "documentation"
    changelog: "documentation/CHANGELOG.md"
  - key: "presentation"
    changelog: "presentation/CHANGELOG.md"
