policies:
  - type: "commit"
    spec:
      conventional:
        types:
          - "feat"
          - "fix"
          - "chore"
          - "style"
          - "refactor"
          - "tests"
          - "docs"
          - "build"
          - "ci"
          - "revert"
        scopes:
          - ".+"
      header:
        imperative: true
      spellcheck:
        locale: "UK"
      dco: true
